modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="kobolds"
version="2.8.3"
displayName="Kobolds"
credits="Jusey1, Giodude1580, Burack, Lorian Ross"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"
description="Tiny Lizards"

[[dependencies.kobolds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




